language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
  
cache:
  directories:
  - "$HOME/.composer/cache"

branches:
  only:
    - master
    - develop

install:
  - composer self-update && composer --version
  - composer update --prefer-source $DEPENDENCIES

before_script:
 - ./.travis/run.sh
 - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

notifications:
  email: antonino.visalli@gmail.com
  
matrix:
  fast_finish: true
  allow_failures:
    - php: 7